Signed-off-by: IamLRBA <jerrylarubafestus@gmail.com>
OpenElements/open-elements-website pull request #142
Opened 2024-12-11 02:00 UTC by IamLRBA

Added Keywords as Metadata
As per issue #59 
cc 
@Jexsie 
@Ndacyayisenga-droid

2024-12-11 09:48 UTC, Jexsie commented on content/about/index.de.md
> +keywords:
`keywords = ["Open Source", "Java", "OSS", "Open Source Unterstützung", "Java Unterstützung"]`

2024-12-11 09:49 UTC, Jexsie commented on content/about/index.md
> +  - "Java Support"
same here

2024-12-12 05:36 UTC, IamLRBA commented
@Jexsie , I have made the changes you requested.

2024-12-12 05:36 UTC, IamLRBA commented on content/about/index.md
> +  - "Java Support"
Changes done

2024-12-12 07:19 UTC, Jexsie requested changes

2024-12-12 07:19 UTC, Jexsie commented on content/about/index.de.md
> +section_engagement_title: "Unser Engagement"
Why is this changing?

2024-12-13 22:52 UTC, closed without merging